# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-29 18:39
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealersDetails',
            fields=[
                ('dealer_number', models.AutoField(primary_key=True, serialize=False)),
                ('dealer_name', models.CharField(max_length=50)),
                ('dealer_phone_number', models.BigIntegerField(blank=True, null=True)),
                ('dealer_email', models.CharField(blank=True, max_length=50, null=True)),
                ('dealer_address', models.CharField(blank=True, max_length=100, null=True)),
                ('total_transaction', models.FloatField(default=0, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ItemDetails',
            fields=[
                ('item_number', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('default_cost_price', models.FloatField(blank=True, null=True)),
                ('default_selling_price', models.FloatField(blank=True, null=True)),
                ('current_stock', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseDetails',
            fields=[
                ('invoice_date_and_time', models.DateTimeField(default=datetime.datetime(2018, 3, 29, 18, 39, 58, 602309, tzinfo=utc))),
                ('invoice_number', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintain_records.DealersDetails')),
                ('invoice_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalesDetails',
            fields=[
                ('invoice_date_and_time', models.DateTimeField(default=datetime.datetime(2018, 3, 29, 18, 39, 58, 603812, tzinfo=utc))),
                ('invoice_number', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintain_records.DealersDetails')),
                ('invoice_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
